[package]
name = "lunatic-log"
version = "0.2.3"
edition = "2021"
description = "A logging library for lunatic Rust applications"
repository = "https://github.com/lunatic-solutions/logger-rs"
categories = ["wasm", "development-tools::debugging"]
license = "Apache-2.0/MIT"
readme = "Readme.md"


[dependencies]
ansi_term = "0.12"
chrono = "0.4"
lunatic = "^0.10"
serde = { version = "1.0", features = ["derive"] }

[package.metadata.docs.rs]
targets = ["wasm32-wasi"]
